version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: legalbot-backend
    ports:
      - "8705:8705"
    env_file:
      - backend/.env
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile.frontend
    container_name: legalbot-frontend
    ports:
      - "8602:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: legalbot-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Google@123
      POSTGRES_DB: legal_chunks_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      # 👇 Mount init.sql so DB auto-creates tables on first startup
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
