# ==============================
# ⚖️ LegalBOT - Local Docker Compose
# ==============================

name: legalbot          # <---- Fixes prefixed volume names!

services:
  # ===========================
  # 🗄️ PostgreSQL Database
  # ===========================
  db:
    image: postgres:16-alpine
    container_name: legalbot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Google@123
      POSTGRES_DB: legal_chunks_db
    volumes:
      - legalbot_pgdata:/var/lib/postgresql/data
      - ./legalbot/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # ===========================
  # 🚀 Backend (FastAPI)
  # ===========================
  backend:
    container_name: legalbot-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./legalbot/backend/.env
    environment:
      APP_ENV: dev
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: legal_chunks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Google@123
      FRONTEND_URL: http://localhost:8602
      GOOGLE_REDIRECT_URI: http://localhost:8705/api/v1/auth/google/callback
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8705:8705"
    volumes:
      - ./legalbot/backend/app:/app/app
    restart: unless-stopped

  # ===========================
  # 💻 Frontend (React / Vite)
  # ===========================
  frontend:
    container_name: legalbot-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8705/api/v1
    depends_on:
      - backend
    ports:
      - "8602:80"
    restart: unless-stopped

# ===========================
# 🧱 Persistent Volumes
# ===========================
volumes:
  legalbot_pgdata:
