services:
  db:
    image: postgres:16-alpine
    container_name: legalbot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Google@123      # raw password used by Postgres internally
      POSTGRES_DB: legal_chunks_db
    ports:
      - "5433:5432"                      # host:container — host 5433 for local tools
    volumes:
      - legalbot_pgdata:/var/lib/postgresql/data
    networks:
      - legalbot-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: legalbot-backend
    ports:
      - "8705:8705"
    env_file:
      - ./legalbot/backend/.env.local
    depends_on:
      - db
    networks:
      - legalbot-net

volumes:
  legalbot_pgdata:

networks:
  legalbot-net:
    driver: bridge
