services:
  backend:
    volumes:
      - ./backend/app:/app/app
    environment:
      - ENV=dev
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8705"

  frontend:
    volumes:
      - ./web:/usr/share/nginx/html
